<?php

namespace Database\Seeders;

use App\Enums\JobGroup;
use App\Enums\JobType;
use App\Models\Guarantor\GuarantorToProductType;
use Illuminate\Database\Seeder;

class GuarantorToProductTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataMany = [
            [
                'guarantor_id' => 1,
                'product_id' => 1,
                'product_type_id' => 1,
                'no' => 1,
                'code_product' => '14',
                'code' => '90.01',
                'name' => 'Jaminan Penawaran',
                'job_group' => JobGroup::KONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Penawaran Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],
            [
                'guarantor_id' => 1,
                'product_id' => 1,
                'product_type_id' => 1,
                'no' => 1,
                'code_product' => '14',
                'code' => '90.02',
                'name' => 'Jaminan Penawaran',
                'job_group' => JobGroup::NONKONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Penawaran Non Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],
            [
                'guarantor_id' => 1,
                'product_id' => 1,
                'product_type_id' => 2,
                'no' => 4,
                'code_product' => '14',
                'code' => '91.01',
                'name' => 'Jaminan Pelaksanaan',
                'job_group' => JobGroup::KONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Pelaksanaan Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,

            ],
            [
                'guarantor_id' => 1,
                'product_id' => 1,
                'product_type_id' => 2,
                'no' => 4,
                'code_product' => '14',
                'code' => '91.02',
                'name' => 'Jaminan Pelaksanaan',
                'job_group' => JobGroup::NONKONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Pelaksanaan Non Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],

            [
                'guarantor_id' => 1,
                'product_id' => 2,
                'product_type_id' => 1,
                'no' => 1,
                'code_product' => '15',
                'code' => '90.01',
                'name' => 'Jaminan Penawaran',
                'job_group' => JobGroup::KONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Penawaran Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],
            [
                'guarantor_id' => 1,
                'product_id' => 2,
                'product_type_id' => 1,
                'no' => 1,
                'code_product' => '15',
                'code' => '90.02',
                'name' => 'Jaminan Penawaran',
                'job_group' => JobGroup::NONKONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Penawaran Non Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],
            [
                'guarantor_id' => 1,
                'product_id' => 2,
                'product_type_id' => 2,
                'no' => 4,
                'code_product' => '15',
                'code' => '91.01',
                'name' => 'Jaminan Pelaksanaan',
                'job_group' => JobGroup::KONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Pelaksanaan Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],
            [
                'guarantor_id' => 1,
                'product_id' => 2,
                'product_type_id' => 2,
                'no' => 4,
                'code_product' => '15',
                'code' => '91.02',
                'name' => 'Jaminan Pelaksanaan',
                'job_group' => JobGroup::NONKONTRUKSI,
                'job_type' => JobType::UNCONDITIONAL,
                'full_name' => 'Jaminan Pelaksanaan Non Konstruksi',
                'minimum_bill' => 0,
                'minimum_payment' => 0,
                'selling_rate' => 0,
                'pay_rate' => 0,
                'sales_administration' => 0,
                'payment_administration' => 0,
                'stamp_duty' => 0,
                'management_fee' => 0,
                'minimum_management_fee' => 0,
                'broken_rate' => 0,
                'revised_rate' => 0,
            ],
        ];

        foreach ($dataMany as $data) {
            GuarantorToProductType::create($data);
        }
    }
}
