<?php

namespace Database\Seeders;

use App\Models\Guarantor\Guarantor;
use Illuminate\Database\Seeder;

class GuarantorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datas = [
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '42',
                'name' => 'PT. Intra Asia Insurance',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 1,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '42',
                'name' => 'PT. Intra Asia Insurance Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],

            // Asuransi tambahan supaya sistem tidak hanya terintegrasi dengan 1 asuransi.
            // Setiap headquarter langsung diikuti 1 baris cabang (headquarter_id merujuk
            // ke id headquarter-nya) mengikuti pola id deterministik pada fresh seed:
            // id 3/4, 5/6, 7/8, 9/10, 11/12, 13/14.
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '43',
                'name' => 'PT Arthagraha General Insurance',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 3,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '43',
                'name' => 'PT Arthagraha General Insurance Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '44',
                'name' => 'PT Asuransi Bangun Askrida',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 5,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '44',
                'name' => 'PT Asuransi Bangun Askrida Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '45',
                'name' => 'PT Asuransi Rama Satria Wibawa',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 7,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '45',
                'name' => 'PT Asuransi Rama Satria Wibawa Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '46',
                'name' => 'PT Asuransi Astra Buana',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 9,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '46',
                'name' => 'PT Asuransi Astra Buana Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '47',
                'name' => 'PT BRI Asuransi Indonesia',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 11,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '47',
                'name' => 'PT BRI Asuransi Indonesia Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '48',
                'name' => 'PT Asuransi Central Asia',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
            [
                'headquarter_id' => 13,
                'province_id' => 11,
                'regency_id' => 97,
                'district_id' => 53,
                'village' => 'Cempaka Mas',
                'postal_code' => '10120',
                'code' => '48',
                'name' => 'PT Asuransi Central Asia Jakarta',
                'email' => 'dummy@gmail.com',
                'address' => 'Jl. Letjen Suprapto Kav. 1',
                'telephone' => '08123456789',
                'fax' => '0211234567',
                'pic' => 'Dummy',
            ],
        ];

        foreach ($datas as $data) {
            Guarantor::query()->create($data);
        }
    }
}
